version: '3.9'

services:
  web:
    build: .
    command: npm run start:web
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - GCP_KEY_BASE64=${GCP_KEY_BASE64}
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/config/gcp-key.json
    volumes:
      - ./config:/usr/src/app/config
    networks:
      - app-network

  worker:
    build: .
    command: npm run start:worker
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8081
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - GCP_KEY_BASE64=${GCP_KEY_BASE64}
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/config/gcp-key.json
    ports:
      - "8081:8081"
    volumes:
      - ./config:/usr/src/app/config
    networks:
      - app-network

networks:
  app-network:
    driver: bridge