version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}  # Using Upstash Redis
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/gcp-key.json
    volumes:
      - ./config/gcp-key.json:/app/config/gcp-key.json
      - outputs:/app/outputs
    networks:
      - app-network

  worker:
    build: .
    restart: always
    command: node --experimental-specifier-resolution=node workers/imageProcessor.js
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}  # Using Upstash Redis
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/gcp-key.json
    volumes:
      - ./config/gcp-key.json:/app/config/gcp-key.json
      - outputs:/app/outputs
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

volumes:
  outputs:

networks:
  app-network:
    driver: bridge
